# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "R+s2bLW24sooyuDsZ6tbxgxLYaaNoVKJV6kW6faoHuCFwFDEVWgjH/J8Px3ujy5Eojl01d153r9VCRSScFjR+hy5CvuVViD18d/Df9BkwJ0iBI1O5YkuY/1URvnwxU9MQE+QP55ql41vugivTNE+UNgWh50DDQYXTmzlFz/gKyMQHUchLq81kxmiKCTk2NIgTdk0XoUGBIkTix18bJyoWCzJ69SsKpF+5bv6sebKTAv0rGo0SVn/W8OoQHfroj4onLejppexvMHfeYfK5uufmmch7+ZSRG46t8PC5sgYJ2tsao0o5eETAuuJQNgQx2mSlP7Wp2U/Lkyi1oqBT6M54Y8Y3kwMdIKpLlLZZ+sfrEaX3veWSkwgGy74Rp7fT7pkqpMWj3DWVM0Sp4A1j0HQY7knQOad+Wo3e46gzA0BTctyi+9gKTrYc7iVfVSMOi5ISjaelSSGN+qDKjGSraAi+7X2XAaVOTRdgXXrdD5YFSqml2+u0dk7ZsBe+zL56vI7OfgJk5lrdteDlE20zby8TL8ERXza5T1SwPMKonhkaHK7m83QKBeexhaBBY9t8elU7qGysfe1gZ+FTmCNVBA6WCXcS7WDjkz3p0uSetcOWKi16NT45IZj7LtYV3n9w49unE46A4Vexvcql0ggltwJ4ZXBQoXHA8VrNxfvTmipFM4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
