appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ca/Hq4FZgk0Qw3CyQgC6AVSbGrP/BgcwR+2pVCBCL62aRLfpg5+7Yb3SynDpK6iYE8cRYqzzV5aeKcLi6JeIqVD6rhcnSQNSG3yrUA2hc49KYq7CjAZB7LlcGPpPBtVP90POx+1e88tbPknxmSpOe1srVHXwjqqwQ3jAkhFQ6nz1GHmtq3Docvh0xI9/99eZX1AbaYF2biWKoRNpTCC/mg0KrqWHMEuAnO7DtWNHro6CXZ34m2hKR2e46oFy/+TaPUfEi2R2uas6yY/5ydOOrsxZ9ucF0TigaTUk4Mo7XemRhgoODyReLcfnLGg9VgyFi0xjM9rypZTveuPa54LHb3gMx9+o915e714Q3mvN7w1DTXrP1J3j7aYaXfdAidUVhMonCT774ksoFds3hkD3i4523I+hP5tOcsA+SIZiZkNUqHxRPK69DR62Bu64yontOt0MQWp/UUWLHhexTRN0pomm23RO9PCbt1jeEMvKlZUBcSzbBk36V5zemznUa+sh0vF0tCMYCrGKbmsR8YosR7y6xk/sHOyfLk6S7/bLhz4+a28/oFJ9xyMCTEXzFUmK5lz6VwlaA25XJBzYwWx9PbRqdJ+w9M71cgqgicmK2e6nqc6CQJNMvu2jBdqYlRx/YsD7a9YP6ALzK3zSXLuCtbLCg2s+Sbq1k8bBHcgNT/Y=}
