travis:
  secure:
    BINSTAR_TOKEN: R+s2bLW24sooyuDsZ6tbxgxLYaaNoVKJV6kW6faoHuCFwFDEVWgjH/J8Px3ujy5Eojl01d153r9VCRSScFjR+hy5CvuVViD18d/Df9BkwJ0iBI1O5YkuY/1URvnwxU9MQE+QP55ql41vugivTNE+UNgWh50DDQYXTmzlFz/gKyMQHUchLq81kxmiKCTk2NIgTdk0XoUGBIkTix18bJyoWCzJ69SsKpF+5bv6sebKTAv0rGo0SVn/W8OoQHfroj4onLejppexvMHfeYfK5uufmmch7+ZSRG46t8PC5sgYJ2tsao0o5eETAuuJQNgQx2mSlP7Wp2U/Lkyi1oqBT6M54Y8Y3kwMdIKpLlLZZ+sfrEaX3veWSkwgGy74Rp7fT7pkqpMWj3DWVM0Sp4A1j0HQY7knQOad+Wo3e46gzA0BTctyi+9gKTrYc7iVfVSMOi5ISjaelSSGN+qDKjGSraAi+7X2XAaVOTRdgXXrdD5YFSqml2+u0dk7ZsBe+zL56vI7OfgJk5lrdteDlE20zby8TL8ERXza5T1SwPMKonhkaHK7m83QKBeexhaBBY9t8elU7qGysfe1gZ+FTmCNVBA6WCXcS7WDjkz3p0uSetcOWKi16NT45IZj7LtYV3n9w49unE46A4Vexvcql0ggltwJ4ZXBQoXHA8VrNxfvTmipFM4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
